### ISSUE TITLE
Rework Botany

### ISSUE THREAD

**Issue by AndrewL97** [Mojave-Sun/mojave-sun#23]

**Comment by Hekzder** [comment]
Basic things can be pre-launch, specifically removing gamey and some base SS13 stuff similar to #17

More advanced parts of this are in line with #26 and is therefore probably also going to be post launch.

**Comment by ArcaneMusic** [comment]
Hey all, Arcane here, also known as the guy who ruined/fixed /tg/'s botany a few months ago. (Link: https://github.com/tgstation/tgstation/pull/50001)
So I guess the question is what features you want/don't want working forward for botany. Since in the fallout universe farming is a full time gig in universe, you probably don't want to simplify it all the way down to how it was before, BUT you also probably don't want to include several of the new /tg/ mechanics.
Here's my thoughts on what you might want to gut, as well as what you would want to expand on.

Gut/Remove:

- Plant Mutations, as neat as they are, is just a bit too science-y, outside of that one vault from New Vegas.
- Grafts could probably go as well, considering that it was built as a way to gene mod plants. ALTERNATIVELY, you could remove the gene alteration aspect of grafts to just make it a way to improve plant stats.
- Variety in terms of plants could be cut down to focus much more on staple plants alongside the mutated plants from fallout, and along with it down the line foods would need some adjusting, but that's covered under #26, as previously mentioned.

Things that could be reworked to better suit the setting:

- Instability as a mechanic could work out pretty well as a kind of "radioactivity stat", so that above 20-40 it would be useful for plant stat modifying, but going too high would contribute to player rads/infecting with sickness, etc.
- From the meeting today, looks like we'll need to figure out how we're doing _manure (tm)_, but in the meantime compost could be worked out for purely plants (Think a resprited version of fermentation like on live /tg/).

Things that would be easy to add to/extend on:

- Speaking of Fermentation, it could be used to great effect here. Real science creates anti-septic (Denatured Alcohol) from just regular alcohol that's been purified into purer ethanol solutions. Fermentation could be used so that grown plants -(Fermenting Barrels)> Drinkable alcohols/wines -(Cooking down over heat)> Denatured Alcohol/Antiseptic/Ethanol
- All of the fallout plants are honestly very easy to implement in once the chemicals are written in.

Most other things like crossbreeding, reagent based chemical drain, etc should work fine within the setting and means of the game, but if anything fancy needs to get done I might be bothered to work on it (Ya know, once /tg/ botany stops sending me horse heads in the mail)
